services:
  app:
    image: oven/bun:1.1.10-alpine
    working_dir: /app
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/app
    env_file: .env
    command: ['bun', 'run', 'dev']

  db:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
