version: '3'

services:
  app:
    image: node:20.14.0-alpine
    working_dir: /usr/src/app
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
    env_file: .env
    command: ['npm', 'run', 'dev']

  db:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
